# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_schelling_rcpp <- function(size, percent_empty, threshold, number_of_groups, max_rounds, seed) {
    .Call('_SchellingR_run_schelling_rcpp', PACKAGE = 'SchellingR', size, percent_empty, threshold, number_of_groups, max_rounds, seed)
}

